import assert from 'node:assert/strict';
import { textAnnotationsByPageEqual } from '../lib/materialWorkspace.ts';
import { applyMaterialHistoryUndo, applyMaterialHistoryRedo } from '../lib/materialHistory.ts';
const old = { id: 'old', text: 'saved text', x: 110, y: 650, width: 190, fontSize: 16, createdAt: 't', updatedAt: 't' };
const placed = { ...old, id: 'new', anchor: 'top-left', text: 'ABC\n123' };
const pages = { '1': [old], '2': [placed] };
const reopened = JSON.parse(JSON.stringify(pages));
assert.deepEqual(reopened, pages);
assert.equal(reopened['1'][0].anchor, undefined);
assert.equal(reopened['2'][0].anchor, 'top-left');
assert.equal(textAnnotationsByPageEqual(pages, reopened), true);
assert.equal(textAnnotationsByPageEqual({ '1': [old] }, { '1': [{ ...old, anchor: 'top-left' }] }), false);
const edit = { kind: 'text-edit', pageNumber: 2, annotationId: 'new', before: placed.text, after: 'ABC\n123\nmore content' };
const edited = applyMaterialHistoryRedo(edit, [], [placed]).textAnnotations[0];
assert.deepEqual({ ...edited, text: placed.text }, placed);
const undo = applyMaterialHistoryUndo(edit, [], [edited]).textAnnotations[0];
assert.deepEqual(undo, placed);
const create = { kind: 'text-create', pageNumber: 2, annotation: placed };
assert.deepEqual(applyMaterialHistoryRedo(create, [], []).textAnnotations, [placed]);
assert.deepEqual(applyMaterialHistoryUndo(create, [], [placed]).textAnnotations, []);
console.log('material-text-anchor-persistence: PASS (new+legacy roundtrip, page ownership, anchor equality, edit/undo/redo geometry)');
